# Menu
menu:
  -
    id: home
    title: Home
    url: /
  -
    id: portfolio
    title: Portfolio
    url: /portfolio
  -
    id: resume
    title: Resume
    url: /resume

# Google Analytics
google_analytics: UA-90449204-2

# Social Accounts
facebook_url: https://www.facebook.com/simon.kallweit
instagram_url: https://www.instagram.com/westlicht
github_url: https://github.com/westlicht
linkedin_url: https://ch.linkedin.com/in/simon-kallweit-b66767128
youtube_url: https://www.youtube.com/westlicht
email_url: mailto:simon.kallweit@gmail.com
